web:
  wordlists:
    directory: /usr/share/seclists/Discovery/Web-Content/directory-list-2.3-medium.txt
    subdomain: /usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt
    vhost: /usr/share/seclists/Discovery/DNS/subdomains-top1million-20000.txt
